### ISSUE TITLE
Errors here

### ISSUE THREAD

**Issue by NecroX1** [flank404/IG-Report-Bot#1]
Hey ,

error 429 is persistent, if possible, provide a more stable version as it is not working at the line 352 792 460 339
![8CF7678C-D35E-47BE-8FD9-535361B20809](https://user-images.githubusercontent.com/110152811/205481732-9a8a082f-45f6-4011-88c0-a61006d1d183.png)

**Comment by halfstackpgr** [comment]
This is not an error. It is simply not working cause of excess reports from the same IP without proxy**Buy the latest tool from him to make it work. His ID is given**
